# Generated by Django 4.1.4 on 2024-05-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
