# Generated by Django 4.1.4 on 2024-06-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
    ]
