# Generated by Django 5.0.2 on 2024-03-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.SlugField(unique=True),
        ),
    ]
