# Generated by Django 4.1.4 on 2024-05-18 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_cat_img_category_cat_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
